num_epochs: 3000
learning_rate: 0.001
alpha: 1
beta: 1000
capture_content_features_from: {'conv4_2'}
capture_style_features_from: {'conv1_1', 'conv2_1', 'conv3_1', 'conv4_1', 'conv5_1'}
early_stopping: True
patience: 50
min_loss: 0.01