num_epochs: 3000
learning_rate: 0.001
alpha: 1
beta: 1e5
capture_content_features_from: {'conv4_2'}  # Usar una capa intermedia para contenido
capture_style_features_from: {'conv1_1', 'conv2_1', 'conv3_1', 'conv4_1', 'conv5_1'}
