num_epochs: 2000
learning_rate: 0.005
alpha: 1
beta: 50
capture_content_features_from: {'conv4_2'}
capture_style_features_from: {'conv4_1', 'conv4_2', 'conv5_1'}
early_stopping: True
patience: 50
min_loss: 0.01