num_epochs: 2000
learning_rate: 0.005
alpha: 1
beta: 100
capture_content_features_from: {'conv1_1', 'conv2_1', 'conv3_1', 'conv4_1', 'conv5_1'}
capture_style_features_from: {'conv1_1', 'conv2_1', 'conv3_1', 'conv4_1', 'conv5_1'}
early_stopping: True
patience: 50
min_loss: 0.01